version: '3'
services:

  pgdb-course:
    environment:
    - DB_NAME=quendless
    - PGDATA=/var/lib/postgresql/data/quendless
    - POSTGRES_PASSWORD=123456
    image: 'postgres:12.3-alpine'
    ports:
    - '5431:5432'
    restart: always
    volumes:
    - ./pgdb:/docker-entrypoint-initdb.d:ro
