spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/quendless"
    username: "postgres"
    password: "123456"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
#  mvc:
#    throw-exception-if-no-handler-found: true
server:
  servlet:
    session:
      timeout: 15m

#springdoc:
#  swagger-ui:
#    path: /swagger_ui